server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.0.1:3306/ivy_academy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&?useSSL=false
    password: need_to_read_from_env
