server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ivy_academy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&?useSSL=false
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl